/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedCircularProgressBar: typeof import('./src/components/ui/animated-circular-progress-bar/AnimatedCircularProgressBar.vue')['default']
    AnimatedTestimonials: typeof import('./src/components/ui/animated-testimonials/AnimatedTestimonials.vue')['default']
    AnimatedTooltip: typeof import('./src/components/ui/animated-tooltip/AnimatedTooltip.vue')['default']
    AppleBlurImage: typeof import('./src/components/ui/apple-card-carousel/AppleBlurImage.vue')['default']
    AppleCard: typeof import('./src/components/ui/apple-card-carousel/AppleCard.vue')['default']
    AppleCardCarousel: typeof import('./src/components/ui/apple-card-carousel/AppleCardCarousel.vue')['default']
    AppleCarouselItem: typeof import('./src/components/ui/apple-card-carousel/AppleCarouselItem.vue')['default']
    BlurReveal: typeof import('./src/components/ui/blur-reveal/BlurReveal.vue')['default']
    BorderBeam: typeof import('./src/components/ui/border-beam/BorderBeam.vue')['default']
    CardBody: typeof import('./src/components/ui/card-3d/CardBody.vue')['default']
    CardContainer: typeof import('./src/components/ui/card-3d/CardContainer.vue')['default']
    CardItem: typeof import('./src/components/ui/card-3d/CardItem.vue')['default']
    CardSpotlight: typeof import('./src/components/ui/card-spotlight/CardSpotlight.vue')['default']
    ChildedComment: typeof import('./src/components/my-ui/comment/ChildedComment.vue')['default']
    Comment: typeof import('./src/components/my-ui/comment/Comment.vue')['default']
    FlickeringGrid: typeof import('./src/components/ui/flickering-grid/FlickeringGrid.vue')['default']
    FlipCard: typeof import('./src/components/ui/flip-card/FlipCard.vue')['default']
    GlowingEffect: typeof import('./src/components/ui/glowing-effect/GlowingEffect.vue')['default']
    GradientButton: typeof import('./src/components/ui/gradient-button/GradientButton.vue')['default']
    HoverButton: typeof import('./src/components/my-ui/hover-button/HoverButton.vue')['default']
    HoverCard: typeof import('./src/components/my-ui/hover-card/HoverCard.vue')['default']
    InteractiveHoverButton: typeof import('./src/components/ui/interactive-hover-button/InteractiveHoverButton.vue')['default']
    LeaveMessageForm: typeof import('./src/components/my-ui/leave-message-form/LeaveMessageForm.vue')['default']
    Loading: typeof import('./src/components/my-ui/loading/loading.vue')['default']
    LocalLoading: typeof import('./src/components/my-ui/loading/LocalLoading.vue')['default']
    Marquee: typeof import('./src/components/ui/marquee/Marquee.vue')['default']
    Meteors: typeof import('./src/components/ui/meteors/Meteors.vue')['default']
    MyModal: typeof import('./src/components/my-ui/modal/MyModal.vue')['default']
    Notifications: typeof import('./src/components/my-ui/notifications/Notifications.vue')['default']
    PaperCard: typeof import('./src/components/my-ui/paper-card/PaperCard.vue')['default']
    RainbowButton: typeof import('./src/components/ui/rainbow-button/RainbowButton.vue')['default']
    ReviewCard: typeof import('./src/components/ui/marquee/ReviewCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SafariCard: typeof import('./src/components/my-ui/safari-card/SafariCard.vue')['default']
    SkeletonLoader: typeof import('./src/components/my-ui/skeleton-loader/SkeletonLoader.vue')['default']
    SparklesText: typeof import('./src/components/ui/sparkles-text/SparklesText.vue')['default']
    TagCard: typeof import('./src/components/my-ui/tag-card/TagCard.vue')['default']
    TextHighlight: typeof import('./src/components/ui/text-highlight/TextHighlight.vue')['default']
    Tooltip: typeof import('./src/components/my-ui/tooltip/Tooltip.vue')['default']
    TracingBeam: typeof import('./src/components/ui/tracing-beam/TracingBeam.vue')['default']
  }
}
